# Default values for ecommerce-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: harbor.tungpd.online/ecommerce
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent

imagePullSecret:
  enabled: true
  registry: harbor.tungpd.online
  username: admin
  password: Attt@123
  email: tungpd@gmail.com

productService:
  name: product-service
  tag: v1
  JAVA_OPTS: -Xmx250m -XX:+UseG1GC
  SPRING_PROFILES_ACTIVE: k8s
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "125Mi"
    limits:
      cpu: "250m"
      memory: "1Gi"


userService:
  name: order-service
  tag: v1
  JAVA_OPTS: -Xmx250m -XX:+UseG1GC
  SPRING_PROFILES_ACTIVE: k8s
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "125Mi"
    limits:
      cpu: "250m"
      memory: "1Gi"

keycloak:
  name: keycloak
  image: quay.io/keycloak/keycloak:23.0.3
  env:
    JAVA_OPTS: -Xms512m -Xmx1g -XX:+UseG1GC
    KC_DB_URL: jdbc:postgresql://34.121.208.150:5432/keycloak
    KC_DB: postgres
    KC_DB_USERNAME: keycloak
    KC_DB_PASSWORD: keycloak