apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartService.name }}
  labels:
    app: {{ .Release.Namespace }}
    module: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
      module: {{ .Values.cartService.name }}
  replicas: {{ .Values.cartService.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
        module: {{ .Values.cartService.name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/{{ .Values.cartService.name }}:{{ .Values.cartService.tag | default .Chart.AppVersion }}"
          name: {{ .Values.cartService.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.cartService.JAVA_OPTS }}  # Giới hạn dung lượng heap tối đa của JVM và sử dụng Garbage Collector
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.cartService.SPRING_PROFILES_ACTIVE }}
          resources:
            {{- toYaml .Values.cartService.resources | nindent 10 }}
          ports:
            - containerPort: 9999
            - containerPort: 6969
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 6969
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 6969
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 120
      imagePullSecrets:
        - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Namespace }}
    module: {{ .Values.cartService.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Namespace }}
    module: {{ .Values.cartService.name }}
  ports:
    - name: {{ .Values.cartService.name }}-port
      protocol: TCP
      port: 9999
      targetPort: 9999
