apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Values.keycloak.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.keycloak.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.keycloak.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: {{ .Values.keycloak.name }}
          image: {{ .Values.keycloak.image }}
          command: [ "/opt/keycloak/bin/kc.sh" ]
          args:
            - start-dev
            - --import-realm
          env:
            {{ range .Values.keycloak.env }}
            - name: {{ .name}}
              value: {{ .value}}
            {{ end }}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/
              name: realm-data
      volumes:
        - name: realm-data
          configMap:
            name: keycloak-realm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: {{ .Release.Namespace }}
data:
  realm-export.json: |
{{ .Files.Get "realm/realm-export.json" | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Values.keycloak.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 8088
  selector:
    app: {{ .Values.keycloak.name }}
  type: NodePort